# Generated by Django 6.0.1 on 2026-01-31 14:47

from django.db import migrations
import secrets
import string


def generate_class_code():
    """Generate a unique 6-character class code"""
    characters = string.ascii_uppercase + string.digits
    return ''.join(secrets.choice(characters) for _ in range(6))


def populate_class_codes(apps, schema_editor):
    """Populate class codes for existing classes"""
    Class = apps.get_model('professor', 'Class')
    for class_obj in Class.objects.filter(class_code__isnull=True):
        # Generate unique code
        while True:
            code = generate_class_code()
            if not Class.objects.filter(class_code=code).exists():
                class_obj.class_code = code
                class_obj.save()
                break


def reverse_populate_class_codes(apps, schema_editor):
    """Reverse migration - set class codes to None"""
    Class = apps.get_model('professor', 'Class')
    Class.objects.update(class_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_class_class_code_studentclassenrollment'),
    ]

    operations = [
        migrations.RunPython(populate_class_codes, reverse_populate_class_codes),
    ]
