# Generated by Django 6.0.1 on 2026-02-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_auto_20260131_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
