# Generated by Django 6.0.1 on 2026-02-02 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_attendancerecord_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_classes', to='professor.class')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('class_obj', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
